config/routes.rb
Helpdesk::Engine.routes.draw do

  resources :tickets do
  	resources :discussions
  end
  resources :teams
  root to: "tickets#index"
end

app/models/helpdesk/team.rb
module Helpdesk
  class Team < ActiveRecord::Base

  	has_many :tickets
  	
  	validates :title, presence: true, length: { maximum: 100 }
  	validates :email, presence: true, length: { maximum: 30 }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

  	default_scope { where(patron_id: Nimbos::Patron.current_id) }

  end
end

app/models/helpdesk/ticket.rb
module Helpdesk
  class Ticket < ActiveRecord::Base

    # include Tire::Model::Search
    # include Tire::Model::Callbacks

    belongs_to :user, class_name: Helpdesk.user_class
    belongs_to :assigned, class_name: Helpdesk.user_class
    belongs_to :team

    has_many   :ticket_actions, dependent: :destroy
    has_many   :discussions, class_name: Helpdesk.discussion_class, as: :target, dependent: :destroy
    has_many   :documents, class_name: Logistics.document_class, as: :documented, dependent: :destroy

    validates :title, presence: true, length: { maximum: 255 }
    #validates :user_id, presence: true
    #validates :status, presence: true
    validates :desc, presence: true, length: { maximum: 500 }
    validates :status, inclusion: { in: %w(active closed cancelled) }
    #validates :reference, presence: true
    #validates_associated :team
    #validates_associated :assigned

    default_scope { where(patron_id: Nimbos::Patron.current_id) }
    scope :latest, -> { order("created_at desc") }

    before_create :set_initials
    after_create  :send_email_to_team

    def self.search(search_id)
      search = Roster::Search.find(search_id)
      tickets = Helpdesk::Ticket.order(created_at: :desc)
      tickets = tickets.where("reference like ?", "%#{search.filter["reference"]}%") if search.filter["reference"].present?
      tickets = tickets.where("title like ?", "%#{search.filter["title"]}%") if search.filter["title"].present?
      tickets = tickets.where(user_id: search.filter["user_id"]) if search.filter["user_id"].present?
      tickets = tickets.where(assigned_id: search.filter["assigned_id"]) if search.filter["assigned_id"].present?
      tickets = tickets.where(status: search.filter["status"]) if search.filter["status"].present?
      tickets = tickets.where(create_date: search.filter["create_date1"]..search.filter["create_date2"]) if (search.filter["create_date1"].present? && self.filter["create_date2"].present?)
      tickets
    end

    def self.ticket_status
    	%w[open assigned closed]
    end

    def to_s
      reference
    end

    def to_param
      "#{id}-#{title.parameterize}"
    end

private
    def set_initials
      self.reference = Nimbos::Patron.generate_counter("Ticket", nil, nil)
    end

    def send_email_to_team
      Resque.enqueue(TicketMailerWorker, { ticket_id: self.id, patron_id: self.patron_id })
    end
  end
end


    # after_touch() { tire.update_index }
    # index_name { "socialfreight-tickets" }#{Nimbos::Patron.current_id}
    # mapping do
    #   indexes :id, type: :integer, index: :not_analyzed
    #   indexes :patron_id, type: :integer, index: :not_analyzed
    #   indexes :title, analyzer: 'snowball', boost: 100
    #   indexes :desc, analyzer: 'snowball'
    #   indexes :status, index: :not_analyzed
    #   indexes :user do
    #     indexes :name, analyzer: 'snowball'
    #     indexes :avatar, index: :not_analyzed
    #   end
    #   indexes :assigned do
    #     indexes :name, analyzer: 'snowball'
    #   end
    #   indexes :close_date, type: 'date', index: :not_analyzed
    #   indexes :created_at, type: 'date', index: :not_analyzed
    # end

    # def to_indexed_json
    #   to_json(include: { user: { only: [:name] }, assigned: { only: [:name] } })
    # end

    # def self.search(query, page_no=1, per_page=10)
    #   tire.search(load: false, page: page_no, per_page: per_page) do
    #     query { string query } if query.present? #, default_operator: "AND"
    #     filter :term, patron_id: Nimbos::Patron.current_id
    #     sort  { by :created_at, "desc" } if query.blank?
    #     #filter :range, published_at: {lte: Time.zone.now}
    #   end
    # end

    # def self.paginate(options = {})
    #   page(options[:page]).per(options[:per_page])
    # end

app/models/helpdesk/ticket_action.rb
module Helpdesk
  class TicketAction < ActiveRecord::Base

    belongs_to :user, class_name: Helpdesk.user_class
    belongs_to :ticket

    validates :action_code, presence: true, length: { maximum: 30 }
    validates :assigned, length: { maximum: 100 }
    #validates_associated :ticket
    
  end
end

app/controllers/helpdesk/application_controller.rb
module Helpdesk
  class ApplicationController < ::ApplicationController
  	layout "layouts/application"

  	def current_engine
  		"helpdesk"
  	end
  end
end

app/controllers/helpdesk/teams_controller.rb
require_dependency "helpdesk/application_controller"

module Helpdesk
  class TeamsController < ApplicationController
    before_filter :require_login
    def new
      @team= Team.new
    end

    def edit
      @team= Team.find(params[:id])
    end

    def show
      @team = Team.find(params[:id])
    end

    def index
    	@teams = Team.all
      @team  = Team.new
    end

    def create
      @team = Team.new(team_params)
      @team.user_id = current_user.id
      respond_to do |format|
        if @team.save
          format.html { redirect_to @team, notice: t("simple_form.messages.default.created", model: Helpdesk::Team.model_name.human) }
          format.json { render json: @team, status: :created, location: @team }
          format.js { flash.now[:notice] = t("simple_form.messages.default.created", model: Helpdesk::Team.model_name.human) }
        else
          format.html { render action: "new" }
          format.json { render json: @team.errors, status: :unprocessable_entity }
          format.js
        end
      end
    end

    def update
      @team = Team.find(params[:id])
      @team.user_id = current_user.id 
      respond_to do |format|
        if @team.update_attributes(team_params)
          format.html { redirect_to @team, notice: t("simple_form.messages.default.updated", model: Helpdesk::Team.model_name.human) }
          format.json { head :no_content }
          format.js { flash.now[:notice] = t("simple_form.messages.default.updated", model: Helpdesk::Team.model_name.human) }
        else
          format.html { render action: "edit" }
          format.json { render json: @team.errors, status: :unprocessable_entity }
          format.js
        end
      end
    end

    def destroy
      @team = Team.find(params[:id])
      @team.destroy

      respond_to do |format|
        format.html { redirect_to teams_url, notice: t("simple_form.messages.default.deleted", model: Helpdesk::Team.model_name.human) }
        format.json { head :ok }
        format.js { flash[:notice] = t("simple_form.messages.default.deleted", model: Helpdesk::Team.model_name.human) }
      end
    end

    private
    def team_params
      params.require(:team).permit(:title, :email )
    end

  end
end

app/controllers/helpdesk/tickets_controller.rb
require_dependency "helpdesk/application_controller"

module Helpdesk
  class TicketsController < ApplicationController
    
    before_filter :require_login
    before_filter(:only => [:index]) { |c| c.set_tab "helpdesknavigator" unless request.xhr? }

    def index
      @tickets = Helpdesk::Ticket.order("created_at desc").page(params[:page]).per(10)
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @tickets }
      end
    end
  
    def show
      @ticket = Helpdesk::Ticket.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @ticket }
      end
    end
  
    def new
      @ticket = Helpdesk::Ticket.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @ticket }
      end
    end
  
    def edit
      @ticket = Helpdesk::Ticket.find(params[:id])

      respond_to do |format|
        #if params[:nolayout]
        #  format.html { render partial: 'modal_form', locals: { ticket: @ticket } }
        #else
        #  format.html # edit.html.erb
        #end
        format.html
        format.js
        format.json { render json: @ticket }
      end
    end
  
    def create
      @ticket = Helpdesk::Ticket.new(ticket_params)
      @ticket.user_id = current_user.id
      @ticket.status = "active"
 
      respond_to do |format|
        if @ticket.save
          create_action("created")
          format.html { redirect_to @ticket, notice: set_message("created") }
          format.json { render json: @ticket, status: :created, location: @ticket }
        else
          format.html { render action: "new" }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      @ticket = Helpdesk::Ticket.find(params[:id])
      @updatable = true
      check_for_update
      if @updatable
        #ticket status is changing
        if params[:ticket][:status].present? && (@ticket.status != params[:ticket][:status])
          change_status
        end

        #first time ticket is assigning to someone
        if params[:ticket][:assigned_id].present? && (@ticket.assigned_id != params[:ticket][:assigned_id])
          assign_ticket
        end

        respond_to do |format|
          if @ticket.update_attributes(ticket_params)
            format.html { redirect_to @ticket, notice: set_message("updated") }
            format.json { head :no_content }
            format.js   { flash.now[:notice] = set_message("updated") }
          else
            format.html { render action: "edit" }
            format.json { render json: @ticket.errors, status: :unprocessable_entity }
          end
        end
      else
        respond_to do |format|
          format.html { render action: "edit" }
          #TODO burada ticket.errors'e flash[:error] eklenmeli
          #format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @ticket = Helpdesk::Ticket.find(params[:id])
      @ticket.destroy
  
      respond_to do |format|
        format.html { redirect_to tickets_url, notice: set_message("deleted") }
        format.json { head :no_content }
      end
    end

    private
    def check_for_update
      if (params[:ticket][:status] != "open" && @ticket.status == "closed")
        @updatable = false
        flash[:error] = "Ticket is closed, can't update."
      end
    end

    def change_status
      #ticket has been closing
      if params[:ticket][:status] == "closed"
        close_ticket
      end

      #ticket has been re opening
      if params[:ticket][:status] == "open"
        if @ticket.status == "closed"
          reopen_ticket
        end
      end
    end

    def close_ticket
      @ticket.close_date = Date.today
      create_action("closed")
    end

    def reopen_ticket
      unless @ticket.assigned_id.nil?
        params[:ticket][:status] = "assigned"
      end
      @ticket.close_date = nil
      create_action("reopened")
    end

    def assign_ticket
      @ticket.status = "assigned"
      if params[:ticket][:assigned_id] != current_user.id
        @assigned_user = Nimbos::User.find(params[:ticket][:assigned_id])
        create_action("assigned", @assigned_user.to_s)
      else
        create_action("self_assigned")
      end
    end

    def create_action(actionCode, assignedUser=nil)
      @action      = @ticket.ticket_actions.new(action_code: actionCode, assigned: assignedUser)
      @action.user = current_user
      @action.save!
    end

    def ticket_params
      params.require(:ticket).permit(:assigned_id, :close_date, :desc, :status, :title, :team_id)
    end

    def set_message(message_code)
      t("simple_form.messages.defaults.#{message_code}", model: Helpdesk::Ticket.model_name.human)      
    end
  end
end

app/helpers/helpdesk/application_helper.rb
module Helpdesk
  module ApplicationHelper
  end
end

app/helpers/helpdesk/teams_helper.rb
module Helpdesk
  module TeamsHelper
  end
end

app/helpers/helpdesk/tickets_helper.rb
module Helpdesk
  module TicketsHelper
  end
end

app/views/helpdesk/tickets/_actions.html.erb
<li class="btn-group">
  <button type="button" class="btn blue dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
    <span><%= t("simple_form.labels.defaults.action") %></span> <i class="fa fa-angle-down"></i>
  </button>
  <ul class="dropdown-menu pull-right" role="menu">
    <% if ticket.status != "closed" %>
      <li>
        <%= link_to edit_ticket_path(ticket) do %>
          <i class="fa fa-edit"></i><%= t("simple_form.helpers.defaults.edit") %>
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
      	<% if ticket.assigned_id.nil? %>
      	  <%= link_to edit_ticket_path(ticket, nolayout: 1), "data-toggle" => "modal", "data-target" => "#newAgileRecord" do %>
      	    <i class="fa fa-user"></i> <%= t("simple_form.helpers.ticket.assign_to_someone") %>
      	  <% end %>
      	<% else %>
      	  <%= link_to edit_ticket_path(ticket, nolayout: 1), "data-toggle" => "modal", "data-target" => "#newAgileRecord" do %>
      	    <i class="fa fa-random"></i><%= t("simple_form.helpers.ticket.change_responsible") %>
      	  <% end %>
      	<% end %>
      </li>
      <li>
        <%= link_to ticket_path(ticket, "ticket[status]" => "closed"), method: "put" do %>
          <i class="fa fa-folder-close"></i><%= t("simple_form.helpers.defaults.close") %>
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to ticket, :data => {:confirm => t("simple_form.messages.defaults.destroy_confirm")}, :method => :delete do %>
          <i class="fa fa-remove"></i><%= t("simple_form.helpers.defaults.delete") %>
        <% end %>
      </li>
    <% else %>
      <li>
        <%= link_to ticket_path(ticket, "ticket[status]" => "open"), method: "put" do %>
          <i class="fa fa-folder-open"></i><%= t("simple_form.helpers.ticket.reopen") %>
        <% end %>
      </li>
    <% end %>
  </ul>
</li>

app/views/helpdesk/tickets/_breadcrumb.html.erb
<ul class="page-breadcrumb breadcrumb">
	<% if content_for?(:breadcrumb_actions) %>
		<%= yield(:breadcrumb_actions) %>
	<% end %>
  <li>
    <i class="fa fa-sitemap"></i>
    <%= link_to "Home", main_app.root_url %> 
    <i class="fa fa-angle-right"></i>
  </li>
  <li><%= link_to (Helpdesk::Ticket.model_name.human(count: 2)), helpdesk.tickets_path %></li>
</ul>

app/views/helpdesk/tickets/_content.html.erb
<div class="row">

  <div class="col-md-1">
  </div>

  <div class="col-md-11">

    <div class="portlet box grey">
      <% content_for(:portlet_actions, flush: true) do %>
        <%= link_to nimbos.new_discussion_url(ticket_id: ticket.id), class: "btn green btn-sm" do %>
          <%= iconed_link_label(Nimbos::Discussion.model_name.human, "fa-comments", "start") %>
        <% end %>
      <% end %>
      <%= render "shared/portlet_title", title: Nimbos::Discussion.model_name.human(count: 2) %>

      <div id="Helpdesk::Ticket_<%= ticket.id %>_discussions_list" class="portlet-body">
        <ul id="Helpdesk::Ticket_<%= ticket.id %>_discussions">
          <%= render partial: "nimbos/discussions/discussion", collection: ticket.discussions, as: :discussion %>
        </ul>
      </div>
    </div>

    <div class="portlet box grey">
      <% content_for(:portlet_actions, flush: true) do %>
        <%= nil %>
      <% end %>    
      <%= render "shared/portlet_title", title: Helpdesk::TicketAction.model_name.human(count: 2) %>
      <div id="Helpdesk::Ticket_<%= ticket.id %>_actions_list" class="portlet-body">
        <%= render "ticket_actions_list", objects: ticket.ticket_actions %>
      </div>
    </div>

    <div class="portlet box grey">
      <% content_for(:portlet_actions, flush: true) do %>
        <%= link_to arsiv.new_document_path(ticket_id: ticket.id), class: "btn green btn-sm" do %>
          <%= iconed_link_label(Arsiv::Document.model_name.human, "fa-copy", "share") %>
        <% end %>
      <% end %>
      <%= render "shared/portlet_title", title: Arsiv::Document.model_name.human(count: 2) %>

      <div id="ticket_<%= ticket.id %>_documents_list" class="portlet-body">
        <ul id="ticket_<%= ticket.id %>_documents">
          <%= render partial: "arsiv/documents/document", collection: ticket.documents %>
        </ul>
      </div>
    </div>

  </div>

</div>

app/views/helpdesk/tickets/_header.html.erb
<div id="Ticket_#{ticket.id}_profile_header" class="row">

  <div class="col-md-1 col-xs-3 col-sm-3">
    <i class="fa fa-bug fa-4x pull-right"></i>
  </div>
  <div class="col-md-11 col-xs-9 col-sm-9">
    <div class="row">
      <div class="col-md-10 profile-info">
        <h1><%= ticket.reference %></h1>
        <p>
          <strong><%= ticket.title %></strong>
          <br>
          <span style="white-space:pre-wrap"><%= ticket.desc %></span>
        </p>
        <p>
          <i class="fa fa-user"></i>
          <%= t("simple_form.labels.ticket.user") %>:
          <%= link_to user_name(ticket.user), nimbos.user_path(ticket.user) %>
          |
          <i class="fa fa-calendar"></i>
          <%= created_time(ticket.created_at) %>

          <span class="pull-right">
          <i class="fa fa-flag"></i>
          <%= t("tickets.status.#{ticket.status}") %>
          </span>
          <br>
          <% unless ticket.assigned_id.nil? %>
            <i class="fa fa-user"></i>
            <%= t("simple_form.labels.ticket.assigned") %>:<%= link_to user_name(ticket.assigned), nimbos.user_path(ticket.assigned) %>
            <% if ticket.status == "open" %>
              [<i class="fa fa-random"></i>
            <%= link_to t("simple_form.helpers.defaults.change"), helpdesk.edit_ticket_path(ticket), remote: true, "data-toggle" => "modal", "data-target" => "#modalWindow" %>]
              <% end %>
              |
            <i class="fa fa-calendar"></i>
            <%= created_time(ticket.close_date) if ticket.close_date %>
          <% else %>
            <i class="fa fa-random"></i>
            <%= t("simple_form.labels.ticket.not_assigned_yet") %>,
            <%= link_to t("simple_form.labels.ticket.assign_to_someone"), helpdesk.edit_ticket_path(ticket), remote: true, "data-toggle" => "modal", "data-target" => "#modalWindow" %>
          <% end %>
        </p>
      </div>
    </div>
    <hr>
  </div>

</div>

app/views/helpdesk/tickets/_list.html.erb
<div id="tickets_list_div" class="table-responsive">
	<table class="table table-striped table-bordered table-hover" id="tickets_list_table">
	  <thead>
	  	<tr>
		  	<th class="col-md-2"><%= t("simple_form.labels.ticket.reference") %></th>
		  	<th class="col-md-2"><%= t("simple_form.labels.ticket.title") %></th>
		  	<th class="col-md-2"><%= t("simple_form.labels.ticket.user") %></th>
		  	<th class="col-md-2"><%= t("simple_form.labels.ticket.created_at") %></th>
		  	<th class="col-md-1"><%= t("simple_form.labels.ticket.status") %></th>
		  	<th class="col-md-2"><%= t("simple_form.labels.ticket.assigned") %></th>
		  	<th class="col-md-1"><%= t("simple_form.labels.ticket.close_date") %></th>
	  	</tr>
	  </thead>
	  <tbody>
	    <% objects.each do |ticket| %>
		  	<tr>
		  		<td><%= link_to ticket.reference, helpdesk.ticket_path(ticket) %></td>
		  		<td><%= ticket.title %></td>
		  		<td><%= user_name(ticket.user) if ticket.user %></td>
		  		<td><%= created_time(ticket.created_at.to_time) %></td>
		  		<td><%= ticket.status %></td>
		  		<td><%= user_name(ticket.assigned) if ticket.assigned %></td>
		  		<td><%= ticket.close_date %></td>
		  	</tr>
		  <% end %>
	  </tbody>
	  
	 </table>

	<% if objects.respond_to? :current_page %>
	  <ul class="pagination">
	   	<%= paginate objects, remote: true %>
	  </ul>
	<% end %>
</div>

app/views/helpdesk/tickets/_profile.html.erb
<div class="row" id="ticket_<%= ticket.id %>_profile">

  <div class="col-md-12" id="ticket_<%= ticket.id %>_profile_header">
    <%= render partial: "header", locals: { ticket: ticket } %>
  </div>

  <div class="col-md-12 profile-section" id="ticket_<%= ticket.id %>_profile_content">
    <%= render partial: "content", locals: { ticket: ticket } %>
  </div>
</div>

app/views/helpdesk/tickets/_setup_links.html.erb
<div class="dropdown pull-right">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
	  <i class="fa fa-cogs"></i>
	</a>
	<ul class="dropdown-menu">
	  <li><%= link_to Nimbos::Counter.model_name.human, nimbos.new_counter_path(counter_type: "Ticket"), remote: true %></li>
	  <li><%= link_to Helpdesk::Team.model_name.human(count: 2), helpdesk.teams_path %></li>
	</ul>
</div>

app/views/helpdesk/tickets/_ticket.html.erb
<%= render 'helpdesk/tickets/header', ticket: ticket %>

app/views/helpdesk/tickets/_ticket_actions_list.html.erb
<div id="tickets_actions_list_div" class="table-responsive">
	<table class="table table-striped table-bordered table-hover" id="tickets_list_table">
	  <thead>
	  	<th class="col-md-1"><%= %></th>
	  	<th class="col-md-9"><%= t("simple_form.labels.ticket.action_desc") %></th>
	  	<th class="col-md-2"><%= t("simple_form.labels.ticket.action_date") %></th>
	  </thead>
	  <tbody>
	    <% objects.each do |ticket_action| %>
		  	<tr>
		  		<td><%= user_mini_avatar(ticket_action.user) %></td>
		  		<td><%= ticket_action.action_code %></td>
		  		<td><%= ticket_action.created_at %></td>
		  		</tr>
		  <% end %>
	  </tbody>
	  
	 </table>

	<% if objects.respond_to? :current_page %>
	  <ul class="pagination">
	   	<%= paginate objects, remote: true %>
	  </ul>
	<% end %>
</div>

app/views/helpdesk/tickets/edit.html.erb
<div class="row">

  <%= render "shared/page_title", page_title: Helpdesk::Ticket.model_name.human(count: 2), page_small_title: "", model_name: "Helpdesk::Ticket", model_path: "helpdesk/tickets" %>

  <div class="col-md-12">
  	<%= render 'form' %>
  </div>

</div>

app/views/helpdesk/tickets/edit.js.erb
<% if @ticket.errors.present? %>
  toastr.error('<%= j error_messages_for(@ticket) %>');
  $("#messages").show();
  $("#messages").html('<div id="flash_notice" class="alert alert-error"><%= j error_messages_for(@ticket) %></div>');
  $("#messages").fadeOut(4000);
<% else %>
	$("#modalWindow").html("<%= escape_javascript(render 'helpdesk/tickets/modal_form') %>");
	$("#modalWindow").modal();
<% end %>
jQuery(document).ready(function() {       
  App.initAjax();
});

app/views/helpdesk/tickets/index.html.erb
<div id="tickets_index" class="row">

  <% content_for(:breadcrumb_actions, flash: true) do %>
  <%= render "helpdesk/tickets/setup_links" %>
  <%end%>

  <%= render "shared/page_title", page_title: Helpdesk::Ticket.model_name.human(count: 2), page_small_title: "", model_name: "Helpdesk::Ticket", model_path: "helpdesk/tickets" %>

  <div class="inbox">
    <div class="col-md-2">
      <ul class="inbox-nav margin-bottom-10">
        <li class="compose-btn">
          <%= link_to helpdesk.new_ticket_path, class: "btn green" do %>
            <i class="fa fa-bug"></i> <%= t("simple_form.helpers.defaults.new", model: Helpdesk::Ticket.model_name.human) %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="col-md-10">
      <div class="inbox-header">
        <h1 class="pull-left"><%= t("simple_form.labels.defaults.list", model: Helpdesk::Ticket.model_name.human) %></h1>
        <%= render "shared/quick_search_form", model_name: "Helpdesk::Ticket" %>
      </div>

      <div class="inbox-content" id="tickets_list">
        <%= render "helpdesk/tickets/list", objects: @tickets %>
      </div>
    </div>
  </div>
</div>

app/views/helpdesk/tickets/show.html.erb
<div class="row">

  <% content_for(:breadcrumb_actions, flush: true) do %>
    <%= render "actions", ticket: @ticket %>
  <% end %>
  <%= render "shared/page_title", page_title: Helpdesk::Ticket.model_name.human(count: 2), page_small_title: "Ekip arkadaşlarınızdan gelen sistem talepleri", model_name: "Helpdesk::Ticket", model_path: "helpdesk/tickets" %>

	<%= render partial: "profile", locals: { ticket: @ticket } %>

</div>

app/views/helpdesk/tickets/update.js.erb
<% if @ticket.errors.present? %>
  toastr.error('<%= j error_messages_for(@ticket) %>');
  $("#messages").show();
  $("#messages").html('<div id="flash_notice" class="alert alert-error"><%= j error_messages_for(@ticket) %></div>');
  $("#messages").fadeOut(4000);
<% else %>
  $('#ticket_<%= @ticket.id %>_profile_header').html("<%= j render partial: 'header', locals: { ticket: @ticket } %>");
  toastr.info('<%= j flash[:notice] %>');
  $("#messages").show();
  $("#messages").html('<div id="flash_notice" class="alert alert-notice"><%= j flash[:notice] %></div>');
  $("#messages").fadeOut(5000);
  $('#modalWindow').modal('hide');
<% end %>